import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import SectionWrapper from '@/components/shared/SectionWrapper';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        fontSans.variable,
        fontMono.variable,
        'font-sans',
      )}
    >
      <body className="min-h-full h-full w-full bg-background text-foreground">
        <SectionWrapper className="flex min-h-full flex-col">
          {children}
        </SectionWrapper>
      </body>
    </html>
  );
}
